project:
  type: website
  output-dir: docs

website:
  title: "Dr. Kev Hosford"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Curriculum Vitae.qmd
      - text: "Gender Rebels"
        href: https://genderrebels.ie # Add this
  favicon: media/favicon.png
format:
  html:
    theme:
      light: united
      dark: solar
    css: styles.css
    toc: true

editor: visual

