project:
  type: website
  output-dir: docs

website:
  title: "Dr. Kev Hosford"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
format:
  html:
    theme:
      light: united
      dark: solar
    css: styles.css
    toc: true

editor: visual

